* DarkIRC-Runit

Some simple runit scripts to automate starting and stopping the
[[https://darkrenaissance.github.io/darkfi/misc/darkirc/darkirc.html][DarkIRC]] daemon.

** todos

*** TODO do we need to use the command =termux-wake-lock= ?

Can we do it without it?  How badly does android (grapheneOS) want to
kill it when it's in the background?

*** TODO fill-in the following scripts [/]

- [ ] bin/setup.sh
- [ ] bin/darkirc/*

*** TODO sign the sha256sum of the =darkirc.aarch64-android= you bundle with this repo

So that when we clone it, we can now there hasn't been any meddling on
the github's side.

** Setup

Git clone this repo in your termux home directory.  And then =cd= into
the cloned dir.

#+begin_src bash
  git clone https://github.com/k4r4b3y/darkirc-runit.git
  cd darkirc-runit
#+end_src

Then, you should run the install script:

#+begin_src bash
  ./bin/setup.sh

#+end_src

*** bin/setup.sh

Setup script prepares termux for running the

1) runit scripts
2) darkirc daemon

Start by defining the runit-related directories, updating the termux
environment, and then installing the =termux-services= which installs
=runit= along with it:

#+begin_src bash :tangle ./bin/setup.sh :mkdirp yes
  #!/data/data/com.termux/files/usr/bin/bash
  pkg upgrade -y
  pkg install termux-services -y
  homelocalbin_dir="${HOME}/.local/bin"
  runit_dir="${HOME}/.config/sv"
#+end_src

Create the directories for the binary and for the runit service
files if they do not already exist:

#+begin_src bash :tangle ./bin/setup.sh :mkdirp yes
  if [ ! -d "${homelocalbin_dir}" ]; then
    mkdir -p "${homelocalbin_dir}"
  fi

  if [ ! -d "${runit_dir}" ]; then
    mkdir "${runit_dir}"
  fi
#+end_src

Copy the runit scripts into the =${runit_dir}= and make them
executable:

#+begin_src bash :tangle ./bin/setup.sh :mkdirp yes
  # cp bin/darkirc -t ${runit_dir}
  # you need to make the runit scripts executable as well
#+end_src

Copy the =darkirc.aarch64-android= binary into its place and make it
executable:

#+begin_src bash :tangle ./bin/setup.sh :mkdirp yes
  # cp bin/darkirc.aarch64-android -t ${homelocalbin_dir}
  # chmod u+x ${homelocalbin_dir}/darkirc.aarch64-android
#+end_src

** Runit scripts

We use runit to start and stop the =darkirc= daemon running in the
background.  We also use =svloggerd= to keep the redirec the stdout
of =darkirc= daemon to runit logging utility.

-----

[[file:assets/powered_by_emacs.svg][This project is powered by emacs]]
[[file:assets/powered_by_org_mode.svg][This project is powered by orgmode]]

