* DarkIRC-Runit

Some simple runit scripts to automate starting and stopping the
[[https://darkrenaissance.github.io/darkfi/misc/darkirc/darkirc.html][DarkIRC]] daemon.

** todos

*** TODO do we need to use the command =termux-wake-lock= ?

Can we do it without it?  How badly does android (grapheneOS) want to
kill it when it's in the background?

*** DONE fill-in the following scripts [2/2]
CLOSED: [2024-07-22 Mon 16:01]
:LOGBOOK:
- State "DONE"       from "TODO"       [2024-07-22 Mon 16:01]
:END:

- [X] bin/setup.sh
- [X] bin/darkirc/*

*** DONE sign the sha256sum of the =darkirc.aarch64-android= you bundle with this repo
CLOSED: [2024-07-22 Mon 15:59]
:LOGBOOK:
- State "DONE"       from "TODO"       [2024-07-22 Mon 15:59]
:END:

So that when we clone it, we can now there hasn't been any meddling on
the github's side.

*** DONE fix the conf stuff
CLOSED: [2024-07-22 Mon 21:37]
:LOGBOOK:
- State "DONE"       from "TODO"       [2024-07-22 Mon 21:37]
:END:

Don't use the conf file.  Instead, put the env variables into their
runit scripts.  I am having trouble with running the runit service.
Also, don't use ${PREFIX} in runit scripts, use full path.

** Setup

Git clone this repo in your termux home directory.  And then =cd= into
the cloned dir.  Install =perl= so that you can use =shasum -c=
command if you want.

#+begin_src bash
  pkg install git perl gnupg -y
  git clone https://github.com/k4r4b3y/darkirc-runit.git
  cd darkirc-runit
#+end_src

Then, you should run the install script:

#+begin_src bash
  ./bin/setup.sh
#+end_src

During the =setup.sh= script execution, you might see your termux
prompt you with the following:

#+begin_quote
Configuration file '/data/data/com.termux/files/usr/etc/apt/sources.list'

 ==> File on system created by you or by a script.

 ==> File also in package provided by package maintainer.

   What would you like to do about it ?  Your options are:

    Y or I  : install the package maintainer's version

    N or O  : keep your currently-installed version

      D     : show the differences between the versions

      Z     : start a shell to examine the situation

 The default action is to keep your current version.

 *** sources.list (Y/I/N/O/D/Z) [default=N] ?
#+end_quote

Here, you can press =Y= and then hit =enter=.

*** bin/setup.sh

Setup script prepares termux for running the

1) runit scripts
2) darkirc daemon

Start by defining the runit-related directories, updating the termux
environment, and then installing the =termux-services= which installs
=runit= along with it:

#+begin_src bash :tangle ./bin/setup.sh :mkdirp yes :shebang #!/data/data/com.termux/files/usr/bin/bash
  pkg upgrade -y
  pkg install termux-services -y
#+end_src

Define some file and directory paths as variables:

#+begin_src bash :tangle ./bin/setup.sh
  repo_dir="${HOME}/darkirc-runit"
  homelocalbin_dir="${HOME}/.local/bin"
  runit_dir="${HOME}/.config/sv"
  darkirc_bin="darkirc.aarch64-android"
  darkirc_conf="${HOME}/.config/darkfi/darkirc_config.toml"
  svdir="${PREFIX}/var/service"
#+end_src

Create the directories for the binary and for the runit service
files if they do not already exist:

#+begin_src bash :tangle ./bin/setup.sh
  if [ ! -d "${homelocalbin_dir}" ]; then
    mkdir -p "${homelocalbin_dir}"
  fi

  if [ ! -d "${runit_dir}" ]; then
    mkdir -p "${runit_dir}"
  fi
#+end_src

Copy the runit scripts into the =${runit_dir}= and make them
executable:

#+begin_src bash :tangle ./bin/setup.sh
  cp -r ${repo_dir}/bin/darkirc -t ${runit_dir}
  chmod u+x ${runit_dir}/darkirc/run ${runit_dir}/darkirc/log/run
#+end_src

Copy the =darkirc.aarch64-android= binary into its place and make it
executable:

#+begin_src bash :tangle ./bin/setup.sh
  cp -r ${repo_dir}/bin/${darkirc_bin} -t ${homelocalbin_dir}
  chmod u+x ${homelocalbin_dir}/${darkirc_bin}
#+end_src

And execute it the first time IF the config file isn't in its place:

#+begin_src bash :tangle ./bin/setup.sh
  if [ ! -f "${darkirc_conf}" ]; then
    ${homelocalbin_dir}/${darkirc_bin}
  fi
#+end_src

Symlink the runit files to =${SVDIR}=.  

#+begin_src bash :tangle ./bin/setup.sh
  ln -sf ${runit_dir}/darkirc ${svdir}/
#+end_src


** Runit scripts

We use runit to start and stop the =darkirc= daemon running in the
background.  We also use =svloggerd= to keep the redirec the stdout
of =darkirc= daemon to runit logging utility.

*** conf

This file will hold the environment variables.

#+begin_src bash :tangle ./bin/darkirc/conf :mkdirp yes
  # empty for now
#+end_src

*** run

This script starts the =darkirc=.  Redirect the stderr to stdout, so
that we can keep track of the errors with =svloggerd=.

#+begin_src bash :tangle ./bin/darkirc/run :mkdirp yes :shebang #!/data/data/com.termux/files/usr/bin/sh
  homelocalbin_dir="${HOME}/.local/bin"
  darkirc_bin="darkirc.aarch64-android"
  exec 2>&1
  exec ${homelocalbin_dir}/${darkirc_bin}
#+end_src

*** log/run

#+begin_src bash :tangle ./bin/darkirc/log/run :mkdirp yes :shebang #!/data/data/com.termux/files/usr/bin/sh
  svlogger="${PREFIX}/share/termux-services/svlogger"
  exec "${svlogger}" "$@"
#+end_src


-----

[[file:assets/powered_by_emacs.svg][This project is powered by emacs]]
[[file:assets/powered_by_org_mode.svg][This project is powered by orgmode]]

